name: Web Scraping and Email

on:
  schedule:
    - cron: '0 16 * * 1-5'  # Schedule the workflow to run at 1pm UTC, Monday-Friday

jobs:
  scrape_and_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4

    - name: Update pip
      run: python -m pip install --upgrade pip
    
    - name: Install dependencies
      run: pip install bs4 beautifulsoup4 requests openai langchain               

    - name: Use API keys from Github Secrets
      env: 
        OPENAPI_KEY: ${{ secrets.OPENAPI_KEY }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python daily_summary_with_langchain.py